# Generated by Django 3.0.3 on 2020-05-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20200522_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupOwner',
        ),
    ]
